title: Tempe
description: Tempe - A containerized jetstream workflow
theme: just-the-docs

url: https://tgen.github.io/tempe

nav_enabled: true
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

callouts:
  important:
    title: Important
    color: blue

mermaid:
  version: "11.10.1"
