title: Tempe
description: Tempe - A containerized jetstream workflow
theme: just-the-docs

url: https://tgen.github.io/tempe

nav_enabled: true
permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
